name: proyectofinal
description: "Aplicación Flutter para el proyecto final."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  
  flutter: '>=3.16.0'    

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 
  go_router: ^13.0.0      
  provider: ^6.1.1        
  http: ^1.1.0            
  flutter_localizations:  
    sdk: flutter
  lucide_icons: ^0.257.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.9.0
  flutter_secure_storage: ^9.0.0
  path: ^1.9.0
  image_picker: ^1.0.7
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Eso es para el icono de tu app, cuando la pases a telefono

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.jpg #la imagen que aparece en la pagina de iniciar sesion

